In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pylab
import seaborn as sns
%matplotlib inline

In [2]:
import os

DATA_DIR = './data/US_FinancialData'
print(os.listdir(DATA_DIR))

['2014_Financial_Data.csv', '2015_Financial_Data.csv', '2016_Financial_Data.csv', '2017_Financial_Data.csv', '2018_Financial_Data.csv']

In [3]:
raw2014_df = pd.read_csv(DATA_DIR+'/2014_Financial_Data.csv')
raw2015_df = pd.read_csv(DATA_DIR+'/2015_Financial_Data.csv')
raw2016_df = pd.read_csv(DATA_DIR+'/2016_Financial_Data.csv')
raw2017_df = pd.read_csv(DATA_DIR+'/2017_Financial_Data.csv')
raw2018_df = pd.read_csv(DATA_DIR+'/2018_Financial_Data.csv')

In [4]:
raw2014_df

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,-0.0187,-0.0217,0.0359,0.0316,0.1228,0.0000,-0.1746,Consumer Defensive,-9.323276,0
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,NaN,NaN,NaN,NaN,NaN,1.6484,1.7313,Consumer Defensive,-25.512193,0
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.0618,0.0981,0.1886,0.3268,0.2738,0.0000,0.0234,Consumer Defensive,33.118297,1
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.0211,-0.0510,-0.0189,0.1963,-0.0458,0.0000,-0.0060,Consumer Defensive,2.752291,1
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,0.0257,0.0090,0.0215,0.0274,0.1025,0.0000,-0.0220,Consumer Defensive,12.897715,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803,TSRI,4.952987e+07,0.1028,4.125164e+07,8.278229e+06,0.000000e+00,8.253061e+06,8.253061e+06,2.516800e+04,0.000000e+00,...,-0.0384,0.0000,-0.0041,-0.0049,0.0000,0.0000,0.0213,Technology,29.362884,1
3804,TZOO,1.532400e+08,-0.1019,1.917400e+07,1.340660e+08,1.132600e+07,1.125130e+08,1.162560e+08,1.781000e+07,0.000000e+00,...,0.1529,0.0000,-0.1872,0.1823,0.0000,0.2830,-0.0637,Technology,-31.167763,0
3805,USATP,4.200000e+07,NaN,2.700000e+07,1.500000e+07,NaN,1.400000e+07,1.500000e+07,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,-23.558900,0
3806,WSTG,3.407580e+08,0.1344,3.159480e+08,2.481000e+07,0.000000e+00,1.651300e+07,1.651300e+07,8.297000e+06,-4.720000e+05,...,-0.0333,0.1338,0.0023,0.0890,0.0000,0.0000,0.0650,Technology,7.779579,1
3807,WTT,4.033737e+07,0.1925,2.129368e+07,1.904369e+07,3.379920e+06,1.098477e+07,1.436469e+07,4.679002e+06,0.000000e+00,...,-0.0469,0.0455,-0.1646,-0.0226,-0.4594,0.2778,-0.0268,Technology,-34.099613,0

In [5]:
raw2015_df

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2016 PRICE VAR [%],Class
0,PG,7.074900e+10,-0.0491,3.705600e+10,3.369300e+10,0.000000e+00,2.061600e+10,2.264400e+10,1.104900e+10,6.260000e+08,...,-0.2847,-0.2634,-0.1024,-0.1013,-0.1432,0.0000,-0.0394,Consumer Defensive,10.809451,1
1,VIPS,6.193685e+09,0.6587,4.669038e+09,1.524648e+09,1.658481e+08,5.223879e+08,1.205660e+09,3.189877e+08,1.321245e+07,...,28.6759,0.2144,0.1279,0.2946,0.0281,0.5309,0.5179,Consumer Defensive,-21.637010,0
2,KR,1.084650e+11,0.1026,8.551200e+10,2.295300e+10,0.000000e+00,1.716100e+10,1.981600e+10,3.137000e+09,4.880000e+08,...,0.1344,0.0065,0.0415,0.0535,0.0254,0.0000,0.1293,Consumer Defensive,-15.036503,0
3,RAD,2.652838e+10,0.0393,1.895164e+10,7.576732e+09,0.000000e+00,6.695642e+09,6.733788e+09,8.429440e+08,3.976120e+08,...,0.0336,-0.0371,0.2639,1.0266,-0.0344,0.0000,0.0205,Consumer Defensive,4.303799,1
4,GIS,1.763030e+10,-0.0156,1.168110e+10,5.949200e+09,0.000000e+00,3.328000e+09,3.871900e+09,2.077300e+09,3.154000e+08,...,-0.0653,-0.0119,-0.0568,-0.2118,0.0462,0.0000,-0.0421,Consumer Defensive,10.693172,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,TSRI,5.740290e+07,0.1590,4.808743e+07,9.315468e+06,0.000000e+00,8.883003e+06,8.883003e+06,4.324650e+05,0.000000e+00,...,-0.0048,0.0000,0.0360,0.0220,0.0000,0.0000,0.0763,Technology,33.101842,1
4116,TZOO,1.239610e+08,-0.1911,1.814800e+07,1.058130e+08,1.221400e+07,8.977900e+07,1.019930e+08,3.820000e+06,0.000000e+00,...,0.0170,0.0000,-0.2650,-0.4011,4.6580,0.0784,-0.2021,Technology,13.801445,1
4117,USATP,5.800000e+07,NaN,4.100000e+07,1.700000e+07,NaN,1.600000e+07,1.700000e+07,-0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,34.769228,1
4118,WSTG,3.820900e+08,0.1213,3.555170e+08,2.657300e+07,0.000000e+00,1.806300e+07,1.806300e+07,8.510000e+06,-3.680000e+05,...,-0.0306,0.3105,-0.0095,-0.0173,0.0000,0.0000,0.0939,Technology,6.050663,1
4119,WTT,3.310911e+07,-0.1792,1.828123e+07,1.482787e+07,3.957274e+06,1.012356e+07,1.408084e+07,7.470390e+05,0.000000e+00,...,0.0675,-0.0553,-0.0436,0.0347,1.3011,0.1708,-0.0784,Technology,17.177912,1

In [6]:
raw2016_df

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2017 PRICE VAR [%],Class
0,PG,6.529900e+10,-0.0770,3.290900e+10,3.239000e+10,0.000000e+00,1.894900e+10,1.894900e+10,1.344100e+10,5.790000e+08,...,-0.0427,-0.0528,-0.0182,-0.0627,0.0083,0.0000,-0.0809,Consumer Defensive,12.532463,1
1,VIPS,8.148496e+09,0.3156,6.190740e+09,1.957756e+09,2.251378e+08,6.880959e+08,1.567877e+09,3.898789e+08,1.226710e+07,...,0.9234,0.0128,0.1706,0.5109,-0.0139,0.3575,0.3172,Consumer Defensive,4.363319,1
2,KR,1.098300e+11,0.0126,8.549600e+10,2.433400e+10,0.000000e+00,1.794600e+10,2.075800e+10,3.576000e+09,4.820000e+08,...,0.3697,0.0844,0.1115,0.2797,0.0416,0.0000,0.0457,Consumer Defensive,-17.068252,0
3,RAD,2.077024e+10,-0.2171,1.577826e+10,4.991979e+09,0.000000e+00,4.581171e+09,4.621042e+09,3.709370e+08,1.861320e+08,...,0.6322,-0.0645,0.2848,8.5628,0.2581,0.0000,-0.3158,Consumer Defensive,-75.916870,0
4,GIS,1.656310e+10,-0.0605,1.073360e+10,5.829500e+09,0.000000e+00,3.118900e+09,3.270300e+09,2.559200e+09,3.038000e+08,...,-0.0187,-0.0825,-0.0055,-0.0105,-0.0828,0.0000,-0.0628,Consumer Defensive,-1.162942,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4792,TSRI,6.099828e+07,0.0626,5.103888e+07,9.959402e+06,0.000000e+00,9.120526e+06,9.120526e+06,8.388760e+05,0.000000e+00,...,-0.1191,0.0000,0.0027,0.0441,0.0000,0.0000,0.0267,Technology,0.655807,1
4793,TZOO,1.142630e+08,-0.0782,1.385500e+07,1.004080e+08,9.096000e+06,8.112600e+07,9.022200e+07,1.018600e+07,0.000000e+00,...,-0.1209,0.0000,-0.2194,-0.1115,-1.0000,-0.2553,-0.0964,Technology,-35.500002,0
4794,USATP,7.700000e+07,NaN,5.500000e+07,2.200000e+07,NaN,2.200000e+07,2.300000e+07,-1.000000e+06,1.000000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,14.840183,1
4795,WSTG,1.646090e+08,-0.5692,1.372780e+08,2.733100e+07,0.000000e+00,1.871500e+07,1.871500e+07,8.616000e+06,-3.180000e+05,...,0.4233,0.1894,0.2085,0.0012,0.0000,0.0000,0.0361,Technology,-2.854095,0
4796,WTT,3.132700e+07,-0.0538,1.816500e+07,1.316200e+07,4.046000e+06,1.166400e+07,1.571000e+07,-2.548000e+06,0.000000e+00,...,-0.0490,0.0476,0.0210,0.0088,-1.0000,0.0224,0.1522,Technology,29.946527,1

In [7]:
raw2017_df

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2018 PRICE VAR [%],Class
0,PG,6.505800e+10,-0.0037,3.263800e+10,3.242000e+10,0.000000e+00,1.865400e+10,1.865400e+10,1.376600e+10,4.650000e+08,...,0.0505,-0.0195,-0.0529,0.0012,0.0325,0.0000,-0.0156,Consumer Defensive,4.975151,1
1,VIPS,1.102060e+10,0.3525,8.557810e+09,2.462794e+09,2.733452e+08,8.201852e+08,2.056136e+09,4.066575e+08,1.245995e+07,...,0.9219,0.4764,0.5889,1.5821,0.3805,0.2141,0.1920,Consumer Defensive,-56.320000,0
2,KR,1.153370e+11,0.0501,8.950200e+10,2.583500e+10,0.000000e+00,1.916200e+10,2.238300e+10,3.452000e+09,5.220000e+08,...,-0.0490,0.0637,0.0769,0.0071,0.1654,0.0000,0.0678,Consumer Defensive,-0.990449,0
3,RAD,2.292754e+10,0.1039,1.786283e+10,5.064707e+09,0.000000e+00,4.776995e+09,4.816124e+09,2.485830e+08,2.000650e+08,...,0.1063,-0.3365,0.0281,0.0502,-0.5295,0.0000,0.0427,Consumer Defensive,-66.666666,0
4,GIS,1.561980e+10,-0.0570,1.005200e+10,5.567800e+09,0.000000e+00,2.888800e+09,3.069200e+09,2.498600e+09,2.951000e+08,...,0.0509,0.0494,0.0046,-0.0943,0.1246,0.0000,-0.0738,Consumer Defensive,-31.280412,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4955,TSRI,6.257258e+07,0.0258,5.232652e+07,1.024606e+07,0.000000e+00,9.683601e+06,9.683601e+06,5.624630e+05,0.000000e+00,...,-0.0482,0.0000,0.0316,-0.1795,0.0000,0.0000,0.0617,Technology,-12.264152,0
4956,TZOO,1.065240e+08,-0.0677,1.290900e+07,9.361500e+07,9.224000e+06,7.984600e+07,8.907000e+07,4.545000e+06,0.000000e+00,...,-0.1836,0.0000,-0.1468,-0.2138,0.0000,0.0141,-0.0158,Technology,46.716421,1
4957,USATP,1.040000e+08,NaN,7.700000e+07,2.700000e+07,NaN,2.500000e+07,2.700000e+07,0.000000e+00,1.000000e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,-32.220041,0
4958,WSTG,1.605670e+08,-0.0246,1.334910e+08,2.707600e+07,0.000000e+00,1.926300e+07,1.926300e+07,7.813000e+06,-6.990000e+05,...,-0.0934,0.2022,-0.0792,0.0782,0.0000,0.0000,0.0293,Technology,-36.405277,0
4959,WTT,4.607800e+07,0.4709,2.681700e+07,1.926100e+07,4.395000e+06,1.798700e+07,2.238200e+07,-3.121000e+06,2.960000e+05,...,0.7440,-0.2280,0.3241,0.0233,0.0000,0.0863,0.5421,Technology,-27.755104,0

In [8]:
raw2018_df

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2019 PRICE VAR [%],Class
0,CMCSA,9.450700e+10,0.1115,0.000000e+00,9.450700e+10,0.000000e+00,6.482200e+10,7.549800e+10,1.900900e+10,3.542000e+09,...,0.2570,0.0000,0.3426,0.0722,0.7309,0.0000,0.1308,Consumer Cyclical,32.794573,1
1,KMI,1.414400e+10,0.0320,7.288000e+09,6.856000e+09,0.000000e+00,6.010000e+08,3.062000e+09,3.794000e+09,1.917000e+09,...,0.0345,-0.0920,-0.0024,0.0076,-0.0137,0.0000,-0.1265,Energy,40.588068,1
2,INTC,7.084800e+10,0.1289,2.711100e+10,4.373700e+10,1.354300e+10,6.750000e+09,2.042100e+10,2.331600e+10,-1.260000e+08,...,0.1989,0.0387,0.0382,0.1014,-0.0169,0.0390,-0.0942,Technology,30.295514,1
3,MU,3.039100e+10,0.4955,1.250000e+10,1.789100e+10,2.141000e+09,8.130000e+08,2.897000e+09,1.499400e+10,3.420000e+08,...,0.4573,0.1511,0.2275,0.6395,-0.5841,0.1738,0.0942,Technology,64.213737,1
4,GE,1.216150e+11,0.0285,9.546100e+10,2.615400e+10,0.000000e+00,1.811100e+10,4.071100e+10,-1.455700e+10,5.059000e+09,...,-0.2781,-0.2892,-0.1575,-0.4487,-0.2297,0.0000,0.0308,Industrials,44.757840,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,YRIV,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,0.000000e+00,3.755251e+06,3.755251e+06,-3.755251e+06,1.105849e+07,...,0.0000,0.0000,-0.0508,-0.1409,-0.0152,0.0000,-0.2602,Real Estate,-90.962099,0
4388,YTEN,5.560000e+05,-0.4110,0.000000e+00,5.560000e+05,4.759000e+06,5.071000e+06,9.830000e+06,-9.274000e+06,0.000000e+00,...,0.3445,0.0000,-0.2323,-0.8602,0.0000,0.0352,-0.0993,Basic Materials,-77.922077,0
4389,ZKIN,5.488438e+07,0.2210,3.659379e+07,1.829059e+07,1.652633e+06,7.020320e+06,8.672953e+06,9.617636e+06,1.239170e+06,...,0.1605,0.7706,0.2489,0.4074,-0.0968,0.2415,0.8987,Basic Materials,-17.834400,0
4390,ZOM,0.000000e+00,0.0000,0.000000e+00,0.000000e+00,1.031715e+07,4.521349e+06,1.664863e+07,-1.664863e+07,0.000000e+00,...,0.8980,0.0000,0.1568,-0.2200,0.0000,2.7499,0.1457,Industrials,-73.520000,0
4391,ZYME,5.301900e+07,0.0243,0.000000e+00,5.301900e+07,5.668400e+07,2.945700e+07,8.614600e+07,-3.312700e+07,1.660000e+05,...,-0.4185,0.0000,0.8519,0.1325,0.0000,0.3577,0.5880,Healthcare,209.462222,1

In [10]:
merged_df = raw2014_df.merge(raw2015_df, how='left', on='Unnamed: 0')
train_df = merged_df.merge(raw2016_df, how='left', on='Unnamed: 0')

In [11]:
merged_df

,Unnamed: 0,Revenue_x,Revenue Growth_x,Cost of Revenue_x,Gross Profit_x,R&D Expenses_x,SG&A Expense_x,Operating Expenses_x,Operating Income_x,Interest Expense_x,...,Receivables growth_y,Inventory Growth_y,Asset Growth_y,Book Value per Share Growth_y,Debt Growth_y,R&D Expense Growth_y,SG&A Expenses Growth_y,Sector_y,2016 PRICE VAR [%],Class_y
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,-0.2847,-0.2634,-0.1024,-0.1013,-0.1432,0.0000,-0.0394,Consumer Defensive,10.809451,1.0
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,28.6759,0.2144,0.1279,0.2946,0.0281,0.5309,0.5179,Consumer Defensive,-21.637010,0.0
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.1344,0.0065,0.0415,0.0535,0.0254,0.0000,0.1293,Consumer Defensive,-15.036503,0.0
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.0336,-0.0371,0.2639,1.0266,-0.0344,0.0000,0.0205,Consumer Defensive,4.303799,1.0
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,-0.0653,-0.0119,-0.0568,-0.2118,0.0462,0.0000,-0.0421,Consumer Defensive,10.693172,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803,TSRI,4.952987e+07,0.1028,4.125164e+07,8.278229e+06,0.000000e+00,8.253061e+06,8.253061e+06,2.516800e+04,0.000000e+00,...,-0.0048,0.0000,0.0360,0.0220,0.0000,0.0000,0.0763,Technology,33.101842,1.0
3804,TZOO,1.532400e+08,-0.1019,1.917400e+07,1.340660e+08,1.132600e+07,1.125130e+08,1.162560e+08,1.781000e+07,0.000000e+00,...,0.0170,0.0000,-0.2650,-0.4011,4.6580,0.0784,-0.2021,Technology,13.801445,1.0
3805,USATP,4.200000e+07,NaN,2.700000e+07,1.500000e+07,NaN,1.400000e+07,1.500000e+07,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,34.769228,1.0
3806,WSTG,3.407580e+08,0.1344,3.159480e+08,2.481000e+07,0.000000e+00,1.651300e+07,1.651300e+07,8.297000e+06,-4.720000e+05,...,-0.0306,0.3105,-0.0095,-0.0173,0.0000,0.0000,0.0939,Technology,6.050663,1.0
3807,WTT,4.033737e+07,0.1925,2.129368e+07,1.904369e+07,3.379920e+06,1.098477e+07,1.436469e+07,4.679002e+06,0.000000e+00,...,0.0675,-0.0553,-0.0436,0.0347,1.3011,0.1708,-0.0784,Technology,17.177912,1.0

In [15]:
merged_df.columns

Index(['Unnamed: 0', 'Revenue_x', 'Revenue Growth_x', 'Cost of Revenue_x',
       'Gross Profit_x', 'R&D Expenses_x', 'SG&A Expense_x',
       'Operating Expenses_x', 'Operating Income_x', 'Interest Expense_x',
       ...
       'Receivables growth_y', 'Inventory Growth_y', 'Asset Growth_y',
       'Book Value per Share Growth_y', 'Debt Growth_y',
       'R&D Expense Growth_y', 'SG&A Expenses Growth_y', 'Sector_y',
       '2016 PRICE VAR [%]', 'Class_y'],
      dtype='object', length=449)

In [12]:
train_df

,Unnamed: 0,Revenue_x,Revenue Growth_x,Cost of Revenue_x,Gross Profit_x,R&D Expenses_x,SG&A Expense_x,Operating Expenses_x,Operating Income_x,Interest Expense_x,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2017 PRICE VAR [%],Class
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,-0.0427,-0.0528,-0.0182,-0.0627,0.0083,0.0000,-0.0809,Consumer Defensive,12.532463,1
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,0.9234,0.0128,0.1706,0.5109,-0.0139,0.3575,0.3172,Consumer Defensive,4.363319,1
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.3697,0.0844,0.1115,0.2797,0.0416,0.0000,0.0457,Consumer Defensive,-17.068252,0
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.6322,-0.0645,0.2848,8.5628,0.2581,0.0000,-0.3158,Consumer Defensive,-75.916870,0
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,-0.0187,-0.0825,-0.0055,-0.0105,-0.0828,0.0000,-0.0628,Consumer Defensive,-1.162942,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803,TSRI,4.952987e+07,0.1028,4.125164e+07,8.278229e+06,0.000000e+00,8.253061e+06,8.253061e+06,2.516800e+04,0.000000e+00,...,-0.1191,0.0000,0.0027,0.0441,0.0000,0.0000,0.0267,Technology,0.655807,1
3804,TZOO,1.532400e+08,-0.1019,1.917400e+07,1.340660e+08,1.132600e+07,1.125130e+08,1.162560e+08,1.781000e+07,0.000000e+00,...,-0.1209,0.0000,-0.2194,-0.1115,-1.0000,-0.2553,-0.0964,Technology,-35.500002,0
3805,USATP,4.200000e+07,NaN,2.700000e+07,1.500000e+07,NaN,1.400000e+07,1.500000e+07,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,14.840183,1
3806,WSTG,3.407580e+08,0.1344,3.159480e+08,2.481000e+07,0.000000e+00,1.651300e+07,1.651300e+07,8.297000e+06,-4.720000e+05,...,0.4233,0.1894,0.2085,0.0012,0.0000,0.0000,0.0361,Technology,-2.854095,0
3807,WTT,4.033737e+07,0.1925,2.129368e+07,1.904369e+07,3.379920e+06,1.098477e+07,1.436469e+07,4.679002e+06,0.000000e+00,...,-0.0490,0.0476,0.0210,0.0088,-1.0000,0.0224,0.1522,Technology,29.946527,1

In [14]:
val_df = raw2017_df
test_df = raw2018_df

In [16]:
raw2014_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3808 entries, 0 to 3807
Columns: 225 entries, Unnamed: 0 to Class
dtypes: float64(222), int64(1), object(2)
memory usage: 6.5+ MB

In [250]:
null_vals = (raw2014_df.isna().sum() + raw2015_df.isna().sum() + raw2016_df.isna().sum() + raw2017_df.isna().sum() + raw2018_df.isna().sum())
null_vals_df = pd.DataFrame({'Column': null_vals.index.to_list(), 'N_null': null_vals.tolist()})
null_vals_df['N_null'] = null_vals_df['N_null'].fillna(0)
null_vals_df

                                         Column   N_null
0     10Y Dividend per Share Growth (per Share)   9177.0
1             10Y Net Income Growth (per Share)   9532.0
2           10Y Operating CF Growth (per Share)   9478.0
3                10Y Revenue Growth (per Share)   9532.0
4    10Y Shareholders Equity Growth (per Share)   9680.0
..                                          ...      ...
224                              returnOnAssets   6535.0
225                     returnOnCapitalEmployed   6509.0
226                              returnOnEquity   2338.0
227                     shortTermCoverageRatios  10744.0
228                   totalDebtToCapitalization   2292.0

[229 rows x 2 columns]

In [125]:
null_vals2014_df = pd.DataFrame({'Column': raw2014_df.columns.tolist(), 'N_null': raw2014_df.isna().sum().tolist()})
null_vals2015_df = pd.DataFrame({'Column': raw2015_df.columns.tolist(), 'N_null': raw2015_df.isna().sum().tolist()})
null_vals2016_df = pd.DataFrame({'Column': raw2016_df.columns.tolist(), 'N_null': raw2016_df.isna().sum().tolist()})
null_vals2017_df = pd.DataFrame({'Column': raw2017_df.columns.tolist(), 'N_null': raw2017_df.isna().sum().tolist()})
null_vals2018_df = pd.DataFrame({'Column': raw2018_df.columns.tolist(), 'N_null': raw2018_df.isna().sum().tolist()})

In [126]:
null_vals2014_df

                   Column  N_null
0              Unnamed: 0       0
1                 Revenue      44
2          Revenue Growth     236
3         Cost of Revenue      74
4            Gross Profit      52
..                    ...     ...
220    R&D Expense Growth     247
221  SG&A Expenses Growth     243
222                Sector       0
223    2015 PRICE VAR [%]       0
224                 Class       0

[225 rows x 2 columns]

In [622]:
target_cols = null_vals_df['Column'][null_vals_df['N_null']==0]
important_cols = null_vals_df['Column'][null_vals_df['N_null']<=1500]
important_cols, len(important_cols)

(5                  2015 PRICE VAR [%]
 6                  2016 PRICE VAR [%]
 7                  2017 PRICE VAR [%]
 8                  2018 PRICE VAR [%]
 9                  2019 PRICE VAR [%]
 32          Cash and cash equivalents
 35                              Class
 52                               EBIT
 57                                EPS
 58                        EPS Diluted
 64         Earnings Before Tax Margin
 66                Earnings before Tax
 70                Financing Cash Flow
 76     Goodwill and Intangible Assets
 79                       Gross Margin
 80                       Gross Profit
 92                Investing Cash flow
 107                    Net Income Com
 111    Net cash flow / Change in cash
 112               Operating Cash Flow
 116                  Operating Income
 138                       Receivables
 141       Retained earnings (deficit)
 143                           Revenue
 149                            Sector
 159                      Total assets
 163                 Total liabilities
 166         Total shareholders equity
 167                        Unnamed: 0
 170          Weighted Average Shs Out
 Name: Column, dtype: object,
 30)

In [623]:
target_cols.tolist()

['2015 PRICE VAR [%]',
 '2016 PRICE VAR [%]',
 '2017 PRICE VAR [%]',
 '2018 PRICE VAR [%]',
 '2019 PRICE VAR [%]',
 'Class',
 'Sector',
 'Unnamed: 0']

In [624]:
useful_cols = important_cols.tolist()
useful_cols

['2015 PRICE VAR [%]',
 '2016 PRICE VAR [%]',
 '2017 PRICE VAR [%]',
 '2018 PRICE VAR [%]',
 '2019 PRICE VAR [%]',
 'Cash and cash equivalents',
 'Class',
 'EBIT',
 'EPS',
 'EPS Diluted',
 'Earnings Before Tax Margin',
 'Earnings before Tax',
 'Financing Cash Flow',
 'Goodwill and Intangible Assets',
 'Gross Margin',
 'Gross Profit',
 'Investing Cash flow',
 'Net Income Com',
 'Net cash flow / Change in cash',
 'Operating Cash Flow',
 'Operating Income',
 'Receivables',
 'Retained earnings (deficit)',
 'Revenue',
 'Sector',
 'Total assets',
 'Total liabilities',
 'Total shareholders equity',
 'Unnamed: 0',
 'Weighted Average Shs Out']

In [625]:
raw2014_df.describe()

,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,Earnings before Tax,...,3Y Dividend per Share Growth (per Share),Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,2015 PRICE VAR [%],Class
count,3.764000e+03,3572.000000,3.734000e+03,3.756000e+03,3.672000e+03,3.749000e+03,3.745000e+03,3.753000e+03,3.745000e+03,3.728000e+03,...,3208.000000,3518.000000,3518.000000,3518.000000,3439.000000,3506.000000,3561.000000,3565.000000,3.808000e+03,3808.000000
mean,5.879050e+09,12.954244,3.700973e+09,2.188214e+09,9.401830e+07,9.307406e+08,1.438144e+09,6.748248e+08,1.002018e+08,5.725866e+08,...,0.036206,4.445793,0.164692,2.279999,0.813931,1.361780,0.596529,0.382284,9.751560e+02,0.429097
std,3.901741e+10,705.605473,3.040688e+10,1.159028e+10,6.408912e+08,4.820928e+09,7.305171e+09,3.786291e+09,6.991091e+08,2.793740e+09,...,0.259765,161.135098,2.195115,92.428920,25.630214,18.734301,25.894049,4.696975,4.098461e+04,0.495012
min,-6.276160e+08,-1.773200,-5.455740e+08,-1.105000e+09,-1.500000e+05,0.000000e+00,-1.088448e+09,-6.786000e+09,-2.250000e+08,-8.878000e+09,...,-1.000000,-1.000000,-1.000000,-0.979600,-230.000000,-1.051000,-1.043700,-1.000000,-1.003972e+02,0.000000
25%,5.788880e+07,-0.002350,3.135714e+06,3.092900e+07,0.000000e+00,1.548900e+07,3.106600e+07,-1.308000e+06,0.000000e+00,-3.732902e+06,...,0.000000,-0.045800,0.000000,-0.015400,-0.084550,-0.048200,0.000000,-0.003900,-2.857143e+01,0.000000
50%,4.349010e+08,0.061850,1.414420e+08,1.908760e+08,0.000000e+00,7.381800e+07,1.386610e+08,4.104400e+07,2.563000e+06,2.842700e+07,...,0.000000,0.014250,0.000000,0.062200,0.037100,0.000000,0.000000,0.068800,-5.281842e+00,0.000000
75%,2.393625e+09,0.188875,1.199844e+09,8.922534e+08,9.911000e+06,3.510000e+08,5.885100e+08,2.712980e+08,4.300000e+07,2.193835e+08,...,0.044000,0.205475,0.063850,0.217100,0.141900,0.210300,0.004700,0.220500,1.331484e+01,1.000000
max,1.824698e+12,42138.663900,1.537249e+12,4.621600e+11,1.153700e+10,1.856830e+11,3.056050e+11,1.565540e+11,3.152300e+10,8.720500e+10,...,3.605800,9328.200000,76.625000,5468.426400,1360.125000,729.576600,1542.611000,225.690000,2.418601e+06,1.000000

In [626]:
input_cols = list(set(useful_cols) - set(target_cols))
target_col_clf = 'Class'
input_cols

['Receivables',
 'EBIT',
 'Weighted Average Shs Out',
 'Goodwill and Intangible Assets',
 'EPS',
 'Operating Income',
 'Total liabilities',
 'Operating Cash Flow',
 'Revenue',
 'Gross Margin',
 'Earnings Before Tax Margin',
 'Retained earnings (deficit)',
 'Cash and cash equivalents',
 'Net cash flow / Change in cash',
 'Total assets',
 'Financing Cash Flow',
 'EPS Diluted',
 'Net Income Com',
 'Gross Profit',
 'Earnings before Tax',
 'Investing Cash flow',
 'Total shareholders equity']

In [627]:
target_col_reg2014 = '2015 PRICE VAR [%]'
target_col_reg2015 = '2016 PRICE VAR [%]'
target_col_reg2016 = '2017 PRICE VAR [%]'
target_col_reg2017 = '2018 PRICE VAR [%]'
target_col_reg2018 = '2019 PRICE VAR [%]'

In [628]:
from sklearn.model_selection import train_test_split

In [629]:
# train2014_df, val2014_df = train_test_split(training_df, test_size=0.2)
train2014_df, val2014_df = train_test_split(raw2014_df, test_size=0.2)

# train2015_df, val2015_df = train_test_split(training_df, test_size=0.2)
train2015_df, val2015_df = train_test_split(raw2015_df, test_size=0.2)

# train2016_df, val2016_df = train_test_split(training_df, test_size=0.2)
train2016_df, val2016_df = train_test_split(raw2016_df, test_size=0.2)

# train2017_df, val2017_df = train_test_split(training_df, test_size=0.2)
train2017_df, val2017_df = train_test_split(raw2017_df, test_size=0.2)

# train2018_df, val2018_df = train_test_split(training_df, test_size=0.2)
train2018_df, val2018_df = train_test_split(raw2018_df, test_size=0.2)

In [630]:
train2014_inputs = train2014_df[input_cols]
train2014_targets = train2014_df[target_col_clf]
val2014_inputs = val2014_df[input_cols]
val2014_targets = val2014_df[target_col_clf]
# test2014_inputs = test2014_df[input_cols]
# test2014_targets = test2014_df[target_col_clf]

train2015_inputs = train2015_df[input_cols]
train2015_targets = train2015_df[target_col_clf]
val2015_inputs = val2015_df[input_cols]
val2015_targets = val2015_df[target_col_clf]
# test2015_inputs = test2015_df[input_cols]
# test2015_targets = test2015_df[target_col_clf]

train2016_inputs = train2016_df[input_cols]
train2016_targets = train2016_df[target_col_clf]
val2016_inputs = val2016_df[input_cols]
val2016_targets = val2016_df[target_col_clf]
# test2016_inputs = test2016_df[input_cols]
# test2016_targets = test2016_df[target_col_clf]

train2017_inputs = train2017_df[input_cols]
train2017_targets = train2017_df[target_col_clf]
val2017_inputs = val2017_df[input_cols]
val2017_targets = val2017_df[target_col_clf]
# test2017_inputs = test2017_df[input_cols]
# test2017_targets = test2017_df[target_col_clf]

train2018_inputs = train2018_df[input_cols]
train2018_targets = train2018_df[target_col_clf]
val2018_inputs = val2018_df[input_cols]
val2018_targets = val2018_df[target_col_clf]
# test2018_inputs = test2018_df[input_cols]
# test2018_targets = test2018_df[target_col_clf]

In [631]:
numeric_cols = train2014_inputs.select_dtypes(include = np.number).columns.to_list()
categorical_cols = train2014_inputs.select_dtypes('object').columns.to_list()

In [632]:
numeric_cols

['Receivables',
 'EBIT',
 'Weighted Average Shs Out',
 'Goodwill and Intangible Assets',
 'EPS',
 'Operating Income',
 'Total liabilities',
 'Operating Cash Flow',
 'Revenue',
 'Gross Margin',
 'Earnings Before Tax Margin',
 'Retained earnings (deficit)',
 'Cash and cash equivalents',
 'Net cash flow / Change in cash',
 'Total assets',
 'Financing Cash Flow',
 'EPS Diluted',
 'Net Income Com',
 'Gross Profit',
 'Earnings before Tax',
 'Investing Cash flow',
 'Total shareholders equity']

In [633]:
categorical_cols

[]

In [634]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

In [635]:
imputer = SimpleImputer(fill_value=0)

In [636]:
scaler = MinMaxScaler()

In [637]:
imputer.fit(raw2014_df[numeric_cols])
train2014_inputs = imputer.transform(train2014_inputs)
val2014_inputs = imputer.transform(val2014_inputs)
# test2014_inputs = imputer.transform(test2014_inputs)
imputer.fit(raw2015_df[numeric_cols])
train2015_inputs = imputer.transform(train2015_inputs)
val2015_inputs = imputer.transform(val2015_inputs)
# test2015_inputs = imputer.transform(test2015_inputs)
imputer.fit(raw2016_df[numeric_cols])
train2016_inputs = imputer.transform(train2016_inputs)
val2016_inputs = imputer.transform(val2016_inputs)
# test2016_inputs = imputer.transform(test2016_inputs)
imputer.fit(raw2017_df[numeric_cols])
train2017_inputs = imputer.transform(train2017_inputs)
val2017_inputs = imputer.transform(val2017_inputs)
# test2017_inputs = imputer.transform(test2017_inputs)
imputer.fit(raw2018_df[numeric_cols])
train2018_inputs = imputer.transform(train2018_inputs)
val2018_inputs = imputer.transform(val2018_inputs)
# test2018_inputs = imputer.transform(test2018_inputs)

In [638]:
scaler.fit(raw2014_df[numeric_cols])
train2014_inputs = scaler.transform(train2014_inputs)
val2014_inputs = scaler.transform(val2014_inputs)
# test2014_inputs = scaler.transform(test2014_inputs)
scaler.fit(raw2015_df[numeric_cols])
train2015_inputs = scaler.transform(train2015_inputs)
val2015_inputs = scaler.transform(val2015_inputs)
# test2015_inputs = scaler.transform(test2015_inputs)
scaler.fit(raw2016_df[numeric_cols])
train2016_inputs = scaler.transform(train2016_inputs)
val2016_inputs = scaler.transform(val2016_inputs)
# test2016_inputs = scaler.transform(test2016_inputs)
scaler.fit(raw2017_df[numeric_cols])
train2017_inputs = scaler.transform(train2017_inputs)
val2017_inputs = scaler.transform(val2017_inputs)
# test2017_inputs = scaler.transform(test2017_inputs)
scaler.fit(raw2018_df[numeric_cols])
train2018_inputs = scaler.transform(train2018_inputs)
val2018_inputs = scaler.transform(val2018_inputs)
# test2018_inputs = scaler.transform(test2018_inputs)

c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\rohan\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

# Model

In [695]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC

from sklearn.ensemble import VotingClassifier

from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [640]:
model2014 = LogisticRegression()

In [641]:
model2014.fit(train2014_inputs, train2014_targets)

LogisticRegression()

In [642]:
train2014_preds = model2014.predict(train2014_inputs)
val2014_preds = model2014.predict(val2014_inputs)
# test2014_preds = model2014.predict(test2014_inputs)

In [643]:
train2014_score = accuracy_score(train2014_preds, train2014_targets)
val2014_score = accuracy_score(val2014_preds, val2014_targets)
# test2014_score = accuracy_score(test2014_preds, test2014_targets)
train2014_score, val2014_score, # test2014_score

(0.5712409717662508, 0.5708661417322834)

In [749]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier(random_state=42, max_leaf_nodes=20, max_depth=7)
svm_clf = SVC(kernel='poly', gamma='auto', coef0=1, shrinking=False, probability=True)
xgb_clf = XGBClassifier(n_jobs = -1, random_state=42, n_estimators = 9,
                     learning_rate=0.4, max_depth = 3, subsample=0.9,
                     colsample_bytree = 0.1)
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('xgb', xgb_clf)],
    voting='soft')

# ('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf), ('xgb', xgb_clf)

In [686]:
def predict_scores(train_inputs, train_targets, val_inputs, val_targets, model= voting_clf):
    model.fit(train_inputs, train_targets)
    train_preds = model.predict(train_inputs)
    val_preds = model.predict(val_inputs)
    train_score = accuracy_score(train_preds, train_targets)
    val_score = accuracy_score(val_preds, val_targets)
    return train_score, val_score

In [750]:
train_score, val_score = predict_scores(train2015_inputs, train2015_targets, val2015_inputs, val2015_targets, voting_clf)
train_score, val_score

(0.7621359223300971, 0.7548543689320388)

In [647]:
## 2014
# (0.767564018384767, 0.6233595800524935)   80

## 2015
# (0.8046116504854369, 0.7439320388349514)  100
# (0.7964199029126213, 0.7536407766990292)  50
# (0.7797330097087378, 0.7245145631067961)  20
# (0.8027912621359223, 0.7657766990291263)  80

# (0.7266383495145631, 0.6856796116504854)  1000
# (0.7900485436893204, 0.7451456310679612)  1300
# (0.7988470873786407, 0.7851941747572816)  1500
# (0.7982402912621359, 0.7548543689320388)  1800
# (0.814623786407767, 0.7330097087378641)   2000
# (0.8191747572815534, 0.7669902912621359)  3000
# (0.8152305825242718, 0.7621359223300971)  3500
# (0.8237257281553398, 0.7487864077669902)  4000

# (0.7845873786407767, 0.758495145631068)   1500
# (0.7988470873786407, 0.7621359223300971)  3500
# (0.7879247572815534, 0.758495145631068)   3000

## 2016

## 2017

## 2018